<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SelfStorageSystem.Application\SelfStorageSystem.Application.csproj" />
    <ProjectReference Include="..\SelfStorageSystem.Domain\SelfStorageSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="BackgroundJobs\" />
    <Folder Include="Configuration\" />
    <Folder Include="Dashboard\" />
    <Folder Include="Data\" />
    <Folder Include="Email\" />
    <Folder Include="Extensions\" />
    <Folder Include="Facilities\" />
    <Folder Include="Handovers\" />
    <Folder Include="Identity\" />
    <Folder Include="Jobs\" />
    <Folder Include="Migrations\" />
    <Folder Include="Overdue\" />
    <Folder Include="Payments\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="Renewals\" />
    <Folder Include="Reservations\" />
    <Folder Include="Security\" />
    <Folder Include="Services\" />
    <Folder Include="Time\" />
    <Folder Include="Units\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
  </ItemGroup>

</Project>
