<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SelfStorageSystem.Domain\SelfStorageSystem.Domain.csproj" />
    <ProjectReference Include="..\SelfStorageSystem.Contracts\SelfStorageSystem.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="Common\" />
    <Folder Include="DTOs\" />
    <Folder Include="Email\" />
    <Folder Include="Extensions\" />
    <Folder Include="Features\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Settings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
