<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="Common\" />
    <Folder Include="Customers\" />
    <Folder Include="Dashboard\" />
    <Folder Include="Deposits\" />
    <Folder Include="Facilities\" />
    <Folder Include="Fees\" />
    <Folder Include="Handovers\" />
    <Folder Include="Overdue\" />
    <Folder Include="Payments\" />
    <Folder Include="Renewals\" />
    <Folder Include="Requests\" />
    <Folder Include="Reservations\" />
    <Folder Include="Responses\" />
    <Folder Include="Support\" />
    <Folder Include="Units\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SelfStorageSystem.Domain\SelfStorageSystem.Domain.csproj" />
  </ItemGroup>

</Project>
